### ISSUE TITLE
Any plans to release on npm?

### ISSUE THREAD

**Issue by hkosova** [lornajane/openapi-overlays-js#12]
Even if as v. `0.0.1-alpha`.

**Comment by lornajane** [comment]
Thanks @hkosova! Definitely considering doing that, and I'll take this as encouragement to get on with it :)

**Comment by lornajane** [comment]
Your wish is my command :) [openapi-overlays-js is now on npm](https://www.npmjs.com/package/openapi-overlays-js)

Please let me know how you get on?
