### ISSUE TITLE
Error when updating fields in the OpenAPI info object

### ISSUE THREAD

**Issue by shanti2530** [lornajane/openapi-overlays-js#15]
I am getting an error when trying to apply an overlay that targets a property in the info object within an OpenAPI document. 

The error is `Error applying overlay: Invalid value used as weak map key`.

Overlay used:

```typescript
overlay: 1.0.0
info:
  title: Add a description
  version: 1.0.0
actions:
- target: $.info.description
  update:
    description: Pet description
```

**Comment by lornajane** [comment]
Could you take a look at #7, is it the same thing and does the same solution work for you?

**Comment by shanti2530** [comment]
Yes that worked, thanks!
